<div class="col-md-12">
    <div class="well">
        <form action="/" method="GET">
            <div class="input-group">
                <input type="hidden" name="action" value="search">
                <input type="text" name="query" value="<?php echo isset($query) ? $query : '' ?>" class="form-control" placeholder="Введите запрос">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Искать!</button>
                </span>
            </div><!-- /input-group -->
        </form>
    </div><!-- /.col-lg-6 -->
</div>