<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vk API audio search demonstration :: unofficial</title>

    <!-- Bootstrap -->
    <link href="/asset/css/bootstrap.min.css" rel="stylesheet">
    <style>
        html,body {
            height: 100%;
            width: 100%;
        }
        .app {
            margin: 50px;
        }
    </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="container-fluid">

<div class="row">
    <div class="col-md-10 app">
        <div class="col-md-12">
            <div class="well">
                <form action="/" method="GET">
                    <div class="input-group">
                        <input type="hidden" name="action" value="search">
                        <input type="text" name="query" value="<?php echo isset($query) ? $query : '' ?>" class="form-control" placeholder="Введите запрос">
                        <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Искать!</button>
                </span>
                    </div><!-- /input-group -->
                </form>
            </div><!-- /.col-lg-6 -->
        </div>
        
        <?php echo $content; ?>
    </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/asset/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/asset/js/bootstrap.min.js"></script>
</body>
</html>