<?php if( $tracks ): ?>
    <div class="col-md-12">
        <h1 class="page-header">Найдено <?php echo intval($tracks['count']) ?></h1>
    </div>

    <div class="col-md-12">
        <?php foreach($tracks['items'] as $i => $track): ?>
            <div class="list-group">
                <div class="list-group-item">
                    <em><?php echo $i + 1 ?>.</em>
                    <button class="btn btn-default">
                        <i class="glyphicon glyphicon-play-circle"></i>
                    </button>
                    <?php echo $track['artist'] . ' - ' . $track['title'] ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="col-md-12">
        <div class="well">Ничего не найдено</div>
    </div>
<?php endif ?>
